options:
  rest-ip:
    type: string
    default:
    description: "The IP of the exposed REST service"
  rest-port:
    type: string
    default:
    description: "The port of the exposed REST service"
